version: '3.8'

services:
  cleanmydata_service:
    build:
      context: .
    container_name: cleanmydata_service
    ports:
      - "9000:9000"  # For FastAPI service
    environment:
      - APP_ENV=production
    restart: always
